# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=Temperatures
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=start123
    ports:
      - 3306:3306

  web:
    image: temperatures-web
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=start123
      - DATABASE_NAME=Temperatures
      - DATABASE_PORT=3306
    ports:
      - 8080:8080