spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Temperatures
    username: dbuser
    password: start123
    platform: mysql
    initialize: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: 'create-drop'

logging.level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG

---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialize: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: 'create-drop'